[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/students/*"
  status = 200
  to = "/.functions/students/:splat"
[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"