name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies for front
        run: npm install
        working-directory: ./front

      - name: Run linter for front
        run: npm run lint
        working-directory: ./front

      - name: Install dependencies for api
        run: npm install
        working-directory: ./api

      - name: Run linter for api
        run: npm run lint
        working-directory: ./api

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies for front
        run: npm install
        working-directory: ./front

      - name: Build front
        run: npm run build
        working-directory: ./front

      - name: Install dependencies for api
        run: npm install
        working-directory: ./api

      - name: Build api
        run: npm run build
        working-directory: ./api

  test:
    runs-on: ubuntu-latest

    services:
      web:
        image: node:16
        ports:
          - 5173:5173
        options: >-
          --health-cmd="curl --fail http://localhost:5173/get-on-your-apprenticeship/ || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies for front
        run: npm install
        working-directory: ./front

      - name: Start frontend server
        run: npm run dev
        working-directory: ./front
        env:
          CI: true

      - name: Run Playwright tests
        run: npm run test:e2e
        working-directory: ./front
