name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        folder: [api, front]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          cd ${{ matrix.folder }}
          npm install

      - name: Run linter
        run: |
          cd ${{ matrix.folder }}
          npm run lint

      - name: Run formatter
        run: |
          cd ${{ matrix.folder }}
          npm run format
